version: '3.7'
services:
  node1:
    build:
      context: ./docker/devchain/
    container_name: node1
    ports:
      - 8545:8545
    volumes:
      - ./data/devchain:/data
    networks:
      eth2:
    environment:
      - BLOCK_TIME=2
      - GAS_LIMIT=12000000

  ipfs:
    build:
      context: ./docker/ipfs/
    container_name: ipfs
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs
    networks:
      eth2:

  node2-1:
    image: sigp/lighthouse@sha256:8abac5f1eaed93180fc3a1ff87a711a3c27316b49a3df3bdaf3c5f3e41f2c27e
    container_name: node2-1
    ports:
      - 5052:5052
    networks:
      eth2:
        ipv4_address: 10.20.30.6
    links:
      - node1
    volumes:
      - ./data:/data
    command: >
      lighthouse
      --spec "${SPEC}"
      --debug-level "${DEBUG_LEVEL}"
      bn
      --datadir "${BEACON_DIR}"
      --testnet-dir "${TESTNET_DIR}"
      --http
      --http-address 0.0.0.0
      --libp2p-addresses /ip4/10.20.30.7/tcp/9000,/ip4/10.20.30.8/tcp/9000
      --eth1
      --eth1-endpoint http://node1:8545

  node2-2:
    image: sigp/lighthouse@sha256:8abac5f1eaed93180fc3a1ff87a711a3c27316b49a3df3bdaf3c5f3e41f2c27e
    container_name: node2-2
    ports:
      - 5053:5052
    networks:
      eth2:
        ipv4_address: 10.20.30.7
    volumes:
      - ./data:/data
    command: >
      lighthouse
      --spec "${SPEC}"
      --debug-level "${DEBUG_LEVEL}"
      bn
      --datadir "${BEACON_DIR}-2"
      --testnet-dir "${TESTNET_DIR}"
      --http
      --http-address 0.0.0.0
      --libp2p-addresses /ip4/10.20.30.6/tcp/9000,/ip4/10.20.30.8/tcp/9000
#      --eth1
#      --eth1-endpoint http://node1:8545
#      --boot-nodes $(cat $BEACON_DIR/beacon/network/enr.dat)

  node2-3:
    image: sigp/lighthouse@sha256:8abac5f1eaed93180fc3a1ff87a711a3c27316b49a3df3bdaf3c5f3e41f2c27e
    container_name: node2-3
    ports:
      - 5054:5052
    networks:
      eth2:
        ipv4_address: 10.20.30.8
    volumes:
      - ./data:/data
    command: >
      lighthouse
      --spec "${SPEC}"
      --debug-level "${DEBUG_LEVEL}"
      bn
      --datadir "${BEACON_DIR}-3"
      --testnet-dir "${TESTNET_DIR}"
      --http
      --http-address 0.0.0.0
      --libp2p-addresses /ip4/10.20.30.6/tcp/9000,/ip4/10.20.30.7/tcp/9000
#      --eth1
#      --eth1-endpoint http://node1:8545
#      --boot-nodes $(cat $BEACON_DIR/beacon/network/enr.dat)

  validators1:
    image: sigp/lighthouse@sha256:8abac5f1eaed93180fc3a1ff87a711a3c27316b49a3df3bdaf3c5f3e41f2c27e
    container_name: validators1
    depends_on:
      - node2-1
#    ports:
#      - 30303:30303
    networks:
      eth2:
        ipv4_address: 10.20.30.22
    volumes:
      - ./data:/data
    command: >
      lighthouse
      --spec "${SPEC}"
      --debug-level "${DEBUG_LEVEL}"
      vc
      --datadir "${VALIDATORS_DIR}"
      --secrets-dir "${SECRETS_DIR}"
      --testnet-dir "${TESTNET_DIR}"
      --auto-register
      --server http://node2-1:5052

networks:
  eth2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.30.0/24
